spring.datasource.url=${DB_URL:jdbc:oracle:thin:@techstoredb_high?TNS_ADMIN=src/main/resources/wallet}
spring.datasource.username=${DB_USER:ADMIN}
spring.datasource.password=${DB_PASSWORD:TechStore2024#}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
logging.level.org.springframework.security=TRACE